apiVersion: aicr.fn.crossplane.io/v1beta1
kind: Input
criteriaFrom:
  accelerator: spec.gpuType
  service: spec.cloud
  intent: spec.purpose
providerConfigRef:
  kind: ClusterProviderConfig
  name: gpu-cluster
skipComponents:
- name: nfd
- name: network-operator
- name: nodewright-operator
- name: prometheus-operator-crds
- name: kube-prometheus-stack
- name: k8s-ephemeral-storage-metrics
- name: nvidia-dra-driver-gpu
- name: nvsentinel
- name: prometheus-adapter
- name: kai-scheduler
