---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-aicr
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: function-aicr
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.7.0
